from __future__ import annotations

from au_politics_money.models import SourceRecord


SOURCES: tuple[SourceRecord, ...] = (
    SourceRecord(
        source_id="aec_transparency_home",
        name="AEC Transparency Register",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="financial_disclosure_portal",
        url="https://transparency.aec.gov.au/",
        expected_format="html",
        update_frequency="ongoing",
        priority="core",
        notes="Primary federal disclosure portal for annual, election, referendum, entity, and download pages.",
    ),
    SourceRecord(
        source_id="aec_transparency_downloads",
        name="AEC Download All Disclosure Data",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="bulk_download_index",
        url="https://transparency.aec.gov.au/Download",
        expected_format="html",
        update_frequency="ongoing",
        priority="core",
        notes="Index for bulk annual, election, and referendum disclosure zip downloads.",
    ),
    SourceRecord(
        source_id="aec_annual_detailed_receipts",
        name="AEC Annual Detailed Receipts",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="financial_disclosure_table",
        url="https://transparency.aec.gov.au/AnnualDetailedReceipts",
        expected_format="html_dynamic",
        update_frequency="annual_plus_amendments",
        priority="core",
        notes="Detailed receipts for parties, significant third parties, and associated entities from 1998-99 onwards.",
    ),
    SourceRecord(
        source_id="aec_download_all_annual_data",
        name="AEC All Annual Disclosure Data ZIP",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="bulk_disclosure_zip",
        url="https://transparency.aec.gov.au/Download/AllAnnualData",
        expected_format="zip",
        update_frequency="ongoing",
        priority="core",
        notes="Bulk annual disclosure data export.",
    ),
    SourceRecord(
        source_id="aec_download_all_election_data",
        name="AEC All Election Disclosure Data ZIP",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="bulk_disclosure_zip",
        url="https://transparency.aec.gov.au/Download/AllElectionsData",
        expected_format="zip",
        update_frequency="event_plus_amendments",
        priority="core",
        notes="Bulk election disclosure data export.",
    ),
    SourceRecord(
        source_id="aec_download_all_referendum_data",
        name="AEC All Referendum Disclosure Data ZIP",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="bulk_disclosure_zip",
        url="https://transparency.aec.gov.au/Download/AllReferendumData",
        expected_format="zip",
        update_frequency="event_plus_amendments",
        priority="medium",
        notes="Bulk referendum disclosure data export.",
    ),
    SourceRecord(
        source_id="aec_member_senator_returns",
        name="AEC MP and Senator Annual Returns",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="financial_disclosure_table",
        url="https://transparency.aec.gov.au/MemberOfParliament",
        expected_format="html_dynamic",
        update_frequency="annual_plus_amendments",
        priority="core",
        notes="Annual returns for Members of the House of Representatives and Senators.",
    ),
    SourceRecord(
        source_id="aec_disclosure_threshold",
        name="AEC Disclosure Threshold",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="legal_threshold_reference",
        url="https://www.aec.gov.au/Parties_and_Representatives/public_funding/threshold.htm",
        expected_format="html",
        update_frequency="annual",
        priority="high",
        notes="Disclosure thresholds by financial year.",
    ),
    SourceRecord(
        source_id="aec_fad_reform",
        name="AEC Funding and Disclosure Reform",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="legal_reform_reference",
        url="https://www.aec.gov.au/news/disclosure-legislative-changes.htm",
        expected_format="html",
        update_frequency="as_needed",
        priority="high",
        notes="Explains reforms commencing 2026-07-01.",
    ),
    SourceRecord(
        source_id="aph_members_interests_48",
        name="House Register of Members' Interests, 48th Parliament",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="interests_register",
        url="https://www.aph.gov.au/senators_and_members/members/register",
        expected_format="html_plus_pdf",
        update_frequency="ongoing",
        priority="core",
        notes="Index of current House member interests PDFs.",
    ),
    SourceRecord(
        source_id="aph_senators_interests",
        name="Senate Register of Senators' Interests",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="interests_register",
        url="https://www.aph.gov.au/Parliamentary_Business/Committees/Senate/Senators_Interests/Senators_Interests_Register",
        expected_format="html_plus_pdf",
        update_frequency="ongoing",
        priority="core",
        notes="Current Senate interests register.",
    ),
    SourceRecord(
        source_id="aph_contacts_csv",
        name="Parliament address labels and CSV files",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="people_roster",
        url="https://www.aph.gov.au/Senators_and_Members/Contacting_Senators_and_Members/Address_labels_and_CSV_files",
        expected_format="html_plus_csv",
        update_frequency="ongoing",
        priority="core",
        notes="Current MP and Senator CSV files by name, state, party, and gender.",
    ),
    SourceRecord(
        source_id="aec_federal_boundaries_gis",
        name="AEC Federal Electoral Boundary GIS Data",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="geospatial_boundaries",
        url="https://www.aec.gov.au/Electorates/gis/gis_datadownload.htm",
        expected_format="html_plus_zip_shapefile",
        update_frequency="redistribution",
        priority="core",
        notes="Current and superseded federal electoral boundary downloads.",
    ),
    SourceRecord(
        source_id="they_vote_for_you_api",
        name="They Vote For You API",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="division_vote_api",
        url="https://theyvoteforyou.org.au/help/data",
        expected_format="json_api_docs",
        update_frequency="ongoing",
        priority="high",
        notes="Civic API for people, policies, divisions, and votes. Requires API key.",
    ),
    SourceRecord(
        source_id="aph_hansard",
        name="Parliament of Australia Hansard",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="official_parliamentary_transcript",
        url="https://www.aph.gov.au/Hansard",
        expected_format="html_pdf_xml",
        update_frequency="sitting_days",
        priority="high",
        notes="Official transcript/report context for chamber proceedings; not the sole formal division record.",
    ),
    SourceRecord(
        source_id="aph_house_votes_and_proceedings",
        name="House Votes and Proceedings",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="official_house_decision_record",
        url="https://www.aph.gov.au/Parliamentary_Business/Chamber_documents/HoR/Votes_and_Proceedings",
        expected_format="html_plus_parlinfo_html_pdf",
        update_frequency="sitting_days",
        priority="high",
        notes="Formal House record for proceedings, decisions, attendance, and divisions.",
    ),
    SourceRecord(
        source_id="aph_senate_journals",
        name="Journals of the Senate",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="official_senate_decision_record",
        url=(
            "https://www.aph.gov.au/About_Parliament/Senate/"
            "Powers_practice_n_procedures/~/~/link.aspx"
            "?_id=732F8182C02D4B3699E417F33843A933"
        ),
        expected_format="html_pdf",
        update_frequency="sitting_days",
        priority="high",
        notes="Formal Senate record for proceedings and decisions, including senators voting in divisions.",
    ),
    SourceRecord(
        source_id="open_australia_api",
        name="OpenAustralia API",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="hansard_member_api",
        url="https://www.openaustralia.org.au/api/",
        expected_format="api_docs",
        update_frequency="ongoing",
        priority="medium",
        notes="Legacy civic API for Hansard and member data.",
    ),
    SourceRecord(
        source_id="australian_lobbyists_register",
        name="Australian Government Register of Lobbyists",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="lobbyist_register",
        url="https://www.ag.gov.au/integrity/australian-government-register-lobbyists",
        expected_format="html",
        update_frequency="ongoing",
        priority="high",
        notes="Federal third-party lobbyists and clients.",
    ),
    SourceRecord(
        source_id="centre_public_integrity_lobbyists",
        name="Centre for Public Integrity Lobbyist Register",
        jurisdiction="Commonwealth",
        level="federal",
        source_type="civic_lobbyist_register",
        url="https://publicintegrity.org.au/lobbyist-register/about-2/",
        expected_format="html",
        update_frequency="ongoing",
        priority="medium",
        notes="Civic presentation of Australian Government Register of Lobbyists data.",
    ),
    SourceRecord(
        source_id="asic_companies_dataset",
        name="ASIC Company Dataset",
        jurisdiction="Commonwealth",
        level="national",
        source_type="company_register_extract",
        url="https://www.data.gov.au/data/dataset/asic-companies",
        expected_format="html_plus_csv",
        update_frequency="weekly",
        priority="high",
        notes="Company register extract for entity resolution.",
    ),
    SourceRecord(
        source_id="acnc_register",
        name="ACNC Registered Charities",
        jurisdiction="Commonwealth",
        level="national",
        source_type="charity_register_extract",
        url="https://data.gov.au/data/dataset/acnc-register",
        expected_format="html_plus_csv",
        update_frequency="weekly",
        priority="high",
        notes="Registered charities extract for ABN-backed charity identification.",
    ),
    SourceRecord(
        source_id="abn_lookup",
        name="ABN Lookup",
        jurisdiction="Commonwealth",
        level="national",
        source_type="business_register_lookup",
        url="https://abr.business.gov.au/home",
        expected_format="html",
        update_frequency="ongoing",
        priority="medium",
        notes="Public ABR lookup. Public data does not expose all ANZSIC details.",
    ),
    SourceRecord(
        source_id="abs_anzsic",
        name="ABS ANZSIC Classification",
        jurisdiction="Commonwealth",
        level="national",
        source_type="industry_classification",
        url="https://www.abs.gov.au/statistics/classifications/australian-and-new-zealand-standard-industrial-classification-anzsic",
        expected_format="html_plus_downloads",
        update_frequency="rare",
        priority="high",
        notes="Official Australian and New Zealand industry classification.",
    ),
    SourceRecord(
        source_id="nacc_corrupt_conduct",
        name="NACC What is Corrupt Conduct",
        jurisdiction="Commonwealth",
        level="national",
        source_type="integrity_reference",
        url="https://www.nacc.gov.au/reporting-and-investigating-corruption/what-corrupt-conduct",
        expected_format="html",
        update_frequency="as_needed",
        priority="medium",
        notes="Reference for careful integrity language and corruption definitions.",
    ),
)


def all_sources() -> tuple[SourceRecord, ...]:
    return SOURCES


def get_source(source_id: str) -> SourceRecord:
    for source in SOURCES:
        if source.source_id == source_id:
            return source
    known = ", ".join(source.source_id for source in SOURCES)
    raise KeyError(f"Unknown source_id {source_id!r}. Known sources: {known}")
