#!/usr/bin/env bash
#
# Build a comprehensive `data/seeds/aec_postcode_search_seed.txt` from a
# CC0-licensed public postcode list (Matthew Proctor's `matthewproctor/
# australianpostcodes` GitHub dataset, public domain). The resulting
# seed file lists every unique 4-digit Australian postcode the
# CC0 source publishes, ordered numerically.
#
# Why this script and not Australia Post:
#   `docs/source_licences.md` records that Australia Post's free
#   postcode CSV is non-commercial reference only and explicitly
#   blocked from any redistribution or public postcode lookup. This
#   script avoids it.
#
# Usage:
#   bash scripts/build_postcode_seed_from_cc0.sh
#
# Output:
#   data/seeds/aec_postcode_search_seed.txt
#
# After building, run:
#   bash scripts/expand_postcode_seed.sh \
#       data/seeds/aec_postcode_search_seed.txt \
#       --max-postcodes=200
#
# to fetch the first 200 against the live AEC Electorate Finder. The
# `--max-postcodes` flag is intentional: respect AEC endpoint etiquette
# by staging large runs.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RAW_DIR="${PROJECT_ROOT}/data/raw/cc0_postcode_seed_source"
SEED_FILE="${PROJECT_ROOT}/data/seeds/aec_postcode_search_seed.txt"
TIMESTAMP="$(date -u +"%Y%m%dT%H%M%SZ")"
SOURCE_URL="https://raw.githubusercontent.com/matthewproctor/australianpostcodes/master/australian_postcodes.csv"

mkdir -p "${RAW_DIR}/${TIMESTAMP}"
RAW_CSV="${RAW_DIR}/${TIMESTAMP}/australian_postcodes.csv"
RAW_META="${RAW_DIR}/${TIMESTAMP}/metadata.json"

echo "==> Downloading CC0 postcode list from ${SOURCE_URL}"
curl -sSL "${SOURCE_URL}" -o "${RAW_CSV}"

CSV_SHA="$(shasum -a 256 "${RAW_CSV}" | awk '{print $1}')"
ROW_COUNT="$(wc -l < "${RAW_CSV}" | tr -d ' ')"
UNIQUE_COUNT="$(tail -n +2 "${RAW_CSV}" | awk -F',' 'NF >= 1 { gsub(/"/, "", $1); print $1 }' | grep -E '^[0-9]{4}$' | sort -u | wc -l | tr -d ' ')"

cat > "${RAW_META}" <<META_EOF
{
  "source_url": "${SOURCE_URL}",
  "fetched_at": "${TIMESTAMP}",
  "sha256": "${CSV_SHA}",
  "row_count": ${ROW_COUNT},
  "unique_4digit_postcode_count": ${UNIQUE_COUNT},
  "licence": "Public Domain (CC0)",
  "licence_source": "https://github.com/matthewproctor/australianpostcodes",
  "notes": "Matthew Proctor's Australian-postcodes dataset is published under CC0 (public domain dedication). It is the project's preferred source for a comprehensive, redistribution-friendly Australian postcode list. See docs/data_sources.md for the source-choice rationale."
}
META_EOF

echo "==> Writing seed file with all unique 4-digit postcodes"
{
  cat <<HEADER_EOF
# Source-backed AEC Electorate Finder postcode seed list (comprehensive).
#
# Generated by scripts/build_postcode_seed_from_cc0.sh on ${TIMESTAMP}
# from the Matthew Proctor australianpostcodes CC0 dataset.
#
# Source CSV:
#   ${SOURCE_URL}
#   sha256: ${CSV_SHA}
#   row_count: ${ROW_COUNT} (postcode-locality pairs)
#   unique 4-digit postcodes: ${UNIQUE_COUNT}
#
# Licence: Public Domain (CC0)
# Per-source rationale: docs/data_sources.md (this is the project's
# preferred comprehensive postcode source; Australia Post's CSV is
# blocked per docs/source_licences.md).
#
# Use scripts/expand_postcode_seed.sh with --max-postcodes=N to stage
# bulk runs against the live AEC Electorate Finder. Respect AEC
# endpoint etiquette: the federal pipeline already builds in per-source
# delays; do not parallelise the fetches.
HEADER_EOF
  tail -n +2 "${RAW_CSV}" \
    | awk -F',' 'NF >= 1 { gsub(/"/, "", $1); print $1 }' \
    | grep -E '^[0-9]{4}$' \
    | sort -u
} > "${SEED_FILE}"

echo "==> Wrote ${SEED_FILE}"
echo "    raw archive:  ${RAW_CSV}"
echo "    raw metadata: ${RAW_META}"
echo "    unique 4-digit postcodes: ${UNIQUE_COUNT}"
